### ISSUE TITLE
Unable to disable camera capture programtically

### ISSUE THREAD

**Issue by Presheda** [dyte-in/flutter-sample-app#10]
Video cannot be disabled unless one clicks on the video icon on the UI.

**Comment by feniljain** [comment]
Hey @Presheda,

Thank you for filing an issue, I was trying to reproduce the same, I replaced [this](https://github.com/dyte-in/flutter-sample-app/blob/main/lib/screens/dyte_meeting_page.dart#L66-L69) with:

```dart
			    meeting.events.on('participantJoin', this, (ev, cont) async {
                  DyteParticipant p = ev.eventData as DyteParticipant;
                  print("Participant ${p.name} joined");
                  var meetingSelf = await meeting.self;
                  meetingSelf.disableVideo();
                  print("Disabling video!");
                });
```

And joined the meeting from mobile as `host`. Next as I joined the meeting with same room name from `app.dyte.in`, my participant's video was turned off. Which suggests everything is working perfectly.

Can you give more details on what steps you followed so that I can reproduce it?

**Comment by feniljain** [comment]
Hey @Presheda,

I will close this issue for now, feel free to re-open it if you think your doubt is not yet solved!
